import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { getItems } from "@/components/getItems";
import { createItem } from "@/components/createItem";
import TodoList from "@/components/TodoList";
import { completeItem } from "@/components/completeItem";
import TodoForm from "@/components/TodoForm";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tname, setTname] = useState("");
  const [cname, setCname] = useState("");
  const [data, setData] = useState([]);

  const handleTChange = (e) => {
    setTname(e.target.value);
  };

  const handleCChange = (e) => {
    setCname(e.target.value);
  };

  const handleData = async () => {
    setData(await getItems());
  };

  const onCreate = async (tname, cname) => {
    await createItem(tname, cname);
    handleData();
  };
  const markComplete = async (tname, cname) => {
    await completeItem(tname, cname);
    handleData();
  };
  useEffect(() => {
    (async () => await handleData())();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div className={styles.content}>
            <h1>Todo List App</h1>
            <div>
              {data.length ? (
                <TodoList items={data} markComplete={markComplete} />
              ) : (
                ""
              )}
            </div>
            <TodoForm
              title={tname}
              details={cname}
              onDetailsChange={handleCChange}
              onTitleChange={handleTChange}
              onSubmit={() => onCreate(tname, cname)}
            />
          </div>
        </div>
      </main>
    </>
  );
}
