import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useState } from "react";
import { getItems } from "@/components/getItems";
import { createItem } from "@/components/createItem";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tname, setTname] = useState("");
  const [cname, setCname] = useState("");


  const handleTChange = (e) => {
    setTname(e.target.value);
  };

  const handleCChange = (e) => {
    setCname(e.target.value);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <header>ToDo App</header>
          <div>
            <h1>Write ToDo Item</h1>
            <form>
              <label>
                <input type="text" />
              </label>
            </form>
          </div>
          <div>
            <h1>Title</h1>
            <form>
              <label>
                Type Note:{" "}
                <input type="text" value={tname} onChange={handleTChange} />
              </label>
            </form>
            <h5>Title Content: {tname}</h5>
            <h1>Note Content</h1>
            <form>
              <label>
                Type Note:{" "}
                <input type="text" value={cname} onChange={handleCChange} />
              </label>
            </form>
            <h5>Note Content: {cname}</h5>
            <div className={styles.button}>
              <button onClick = {() => createItem(tname, cname)}>Add Note</button>
            </div>
            <div className={styles.button}>
              <button onClick = {() => getItems()}>Get Previous Notes</button>
            </div>

          </div>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </div>
      </main>
    </>
  );
}
