import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import React, { useEffect, useState } from "react";
import { getItems } from "@/components/getItems";
import { createItem } from "@/components/createItem";
import TodoList from "@/components/TodoList";
import { completeItem } from "@/components/completeItem";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [tname, setTname] = useState("");
  const [cname, setCname] = useState("");
  const [data, setData] = useState([]);

  const handleTChange = (e) => {
    setTname(e.target.value);
  };

  const handleCChange = (e) => {
    setCname(e.target.value);
  };

  const handleData = async () => {
    setData(await getItems());
  };

  const onCreate = async (tname, cname) => {
    await createItem(tname, cname);
    handleData();
  };
  const markComplete = async (tname, cname) => {
    await completeItem(tname, cname);
    handleData();
  };
  useEffect(() => {
    (async () => await handleData())();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <header>ToDo App</header>
          <div>
            <h1>Write ToDo Item</h1>
            <form>
              <label>
                <input type="text" />
              </label>
            </form>
          </div>
          <div>
            <h1>Title</h1>
            <div>
              {data.length && (
                <TodoList items={data} markComplete={markComplete} />
              )}
            </div>
            <form>
              <label>
                Type Note:{" "}
                <input type="text" value={tname} onChange={handleTChange} />
              </label>
            </form>
            <h5>Title Content: {tname}</h5>
            <h1>Note Content</h1>
            <form>
              <label>
                Type Note:{" "}
                <input type="text" value={cname} onChange={handleCChange} />
              </label>
            </form>
            <h5>Note Content: {cname}</h5>
            <div className={styles.button}>
              <button onClick={() => onCreate(tname, cname)}>Add Note</button>
            </div>
            {/* <div className={styles.button}>
              <button onClick={() => handlePrintText()}>
                Get Previous Notes
              </button>
              {JSON.stringify(printText)}
            </div> */}
          </div>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
        </div>
      </main>
    </>
  );
}
